[package]
name = "pi_dirty"
version = "0.2.0"
authors = ["zmythleo <zmythleo@gmail.com>"]
edition = "2021"
description = "Record hierarchy dirty"
repository = "https://github.com/GaiaWorld/pi_dirty.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "pi_dirty", "dirty"]

[dependencies]
pi_map = "0.2"
log = "0.4"
derive_deref = "1.1"